name: Bug Report
description: For users or developers to report any programming issues, such as crashes, errors, or unexpected behavior of ABACUS
labels: [Bug Report]
assignees: [insert assignee here]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: |
      A clear and concise description of what the bug is. The bug may results in:
      - abnormal interruption of the program,
      - systematic or randomized numerical error, or
      - relatively low efficiency.
    placeholder: |
      Example: When running ABACUS with certain input parameters, the program crashes  
      unexpectedly during the SCF calculation ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: |
      A clear and concise description of what you expected to happen.
    placeholder: |
      Example: ABACUS should complete the SCF calculation with the specified input parameters   
      without any errors or crashes ...

- type: textarea
  attributes:
    label: To Reproduce
    description: |
      Steps to reproduce the behavior:
      1. [e.g. clone the source code from ...]
      2. [e.g. configure CMake with options ...]
      3. [e.g. build ABACUS with ...]
      4. [e.g. run ABACUS with ...]

      It is recommended to attach your calculation case here for the developers to reproduce the bug.
    placeholder: |
      Example:  
      1. Clone the source code from https://github.com/deepmodeling/abacus-develop.git     
      2. Configure CMake with options -DBUILD_TESTING=ON ...    
      3. Build ABACUS with cmake --build build -j8 ...    
      4. Run ABACUS with mpirun -np 4 ./abacus ...    

- type: textarea
  attributes:
    label: Environment
    description: |
      - OS: [e.g. Ubuntu 20.04]
      - Compiler: [e.g. gcc 5.1.0]
      - Dependencies: [e.g. Intel MKL, OpenBLAS]
    placeholder: |
      Example:  
      - OS: Ubuntu 20.04  
      - Compiler: gcc 5.1.0  
      - Dependencies: Intel MKL, OpenBLAS  

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context about the problem here.
    placeholder: |
      Example: The issue seems to occur only when using a specific input file, which I have attached below ...

- type: checkboxes
  attributes:
    label: Task list for Issue attackers
    options:
      - label: Verify the issue is not a duplicate.
      - label: Describe the bug.
      - label: Steps to reproduce.
      - label: Expected behavior.
      - label: Error message.
      - label: Environment details.
      - label: Additional context.
      - label: Assign a priority level (low, medium, high, urgent).
      - label: Assign the issue to a team member.
      - label: Label the issue with relevant tags.
      - label: Identify possible related issues.
      - label: Create a unit test or automated test to reproduce the bug (if applicable).
      - label: Fix the bug.
      - label: Test the fix.
      - label: Update documentation (if necessary).
      - label: Close the issue and inform the reporter (if applicable).

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
