name: Docs
description: For users or developers to report issues related to software documentation, such as missing or incomplete documentation, or documentation that is difficult to understand.
labels: [Docs]
assignees: [insert assignee here]
body:
- type: textarea
  attributes:
    label: Details
    description: |
      Please provide details about the documentation issue you are experiencing. Include any relevant information such as the specific section of the documentation, the information that is missing or unclear, and any suggestions for improvement. If you are unsure about what information to provide, please refer to the online manual (check the box below if you have not read it yet).
    placeholder: |
      Example: The documentation for the new xc functional calculations is missing. I have read the online manual, but I am still not sure how to perform the new xc functional calculations. My suggestion is to add a new section to the online manual that describes the new xc functional calculations.
  validations:
      required: true
- type: checkboxes
  attributes:
    label: Have you read the online manual http://abacus.deepmodeling.com/en/latest/
    description: Please check the box below if you have read the online manual before submitting your issue.
    options:
      - label: Yes, I have read the online manual.
        required: true
- type: checkboxes
  attributes:
    label: Task list for Issue attackers (only for developers)
    options:
      - label: Identify the specific section of the documentation with the issue.
      - label: Investigate the issue and determine the root cause.
      - label: Research best practices and potential solutions for the identified issue.
      - label: Update the documentation to address the issue, following the suggested improvement.
      - label: Ensure the updated documentation adheres to the project's documentation standards.
      - label: Test the updated documentation to ensure it is clear and accurate.
      - label: Review and incorporate any relevant feedback from users or developers.
      - label: Publish the updated documentation and notify the issue reporter.
- type: markdown
  attributes:
    value: >
      Thank you for reporting this documentation issue. We will review and update the documentation as necessary. 📚