name: Tests
description: For developers to report issues related to software testing, such as test failures, missing or incomplete tests, or issues with test automation.
labels: [Tests]
assignees: hongriTianqi

body:
- type: textarea
  attributes:
    label: Describe the Testing Issue
    description: |
      Please provide details about the testing issue you are experiencing. Include any relevant information such as the specific test case, the expected and actual results, and any error messages you received. If you have any suggestions for a possible solution, please include them as well.
    placeholder: |
      Example: The test case for the new xc functional calculations is failing. The expected result is 0.0, but the actual result is 0.1. The error message is "Error: The new xc functional calculations are not implemented yet."
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context or screenshots about the testing issue here.

- type: checkboxes
  attributes:
    label: Task list for Issue attackers
    options:
      - label: Understand the testing issue described by the developer.
      - label: Review the specific test case, expected and actual results, and any error messages.
      - label: Identify the root cause of the test failure or issue.
      - label: If a possible solution is suggested, evaluate its feasibility and effectiveness.
      - label: Implement a fix for the test failure or issue, or create a new test case if needed.
      - label: Verify that the fix resolves the testing issue and the test case passes.
      - label: Review and update any relevant documentation, such as test plans or user guides.
      - label: Ensure the testing issue is resolved and close the ticket.
      - label: Share any lessons learned or best practices with the team to prevent similar issues in the future.

- type: markdown
  attributes:
    value: >
      Thank you for reporting this testing issue. We will investigate and do our best to resolve it. 🧪
