name: Container

on:
  push:
    branches:
      - ghcr-test

env:
  CONTAINER: ghcr.io/deepmodeling/test:latest

jobs:
  build_container_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.OWNER }}
          password: ${{ secrets.PAT }}
      - name: Build and Push Container
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.CONTAINER }}
          cache-from: type=registry,ref=${{ env.CONTAINER }}
          cache-to: type=inline
          push: true
